// Static reference — not used at runtime (DB is source of truth)
export const TEAMS_SEED = [
  // TIER 1 — Elite (FIFA #1–16)
  { name: 'France',       tier: 1, flag_emoji: '🇫🇷', confederation: 'UEFA',     fifa_group: 'I', fifa_ranking: 1,  is_debut: false },
  { name: 'Spain',        tier: 1, flag_emoji: '🇪🇸', confederation: 'UEFA',     fifa_group: 'H', fifa_ranking: 2,  is_debut: false },
  { name: 'Argentina',    tier: 1, flag_emoji: '🇦🇷', confederation: 'CONMEBOL', fifa_group: 'J', fifa_ranking: 3,  is_debut: false },
  { name: 'England',      tier: 1, flag_emoji: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', confederation: 'UEFA',     fifa_group: 'L', fifa_ranking: 4,  is_debut: false },
  { name: 'Portugal',     tier: 1, flag_emoji: '🇵🇹', confederation: 'UEFA',     fifa_group: 'K', fifa_ranking: 5,  is_debut: false },
  { name: 'Brazil',       tier: 1, flag_emoji: '🇧🇷', confederation: 'CONMEBOL', fifa_group: 'C', fifa_ranking: 6,  is_debut: false },
  { name: 'Netherlands',  tier: 1, flag_emoji: '🇳🇱', confederation: 'UEFA',     fifa_group: 'F', fifa_ranking: 7,  is_debut: false },
  { name: 'Morocco',      tier: 1, flag_emoji: '🇲🇦', confederation: 'CAF',      fifa_group: 'C', fifa_ranking: 8,  is_debut: false },
  { name: 'Belgium',      tier: 1, flag_emoji: '🇧🇪', confederation: 'UEFA',     fifa_group: 'G', fifa_ranking: 9,  is_debut: false },
  { name: 'Germany',      tier: 1, flag_emoji: '🇩🇪', confederation: 'UEFA',     fifa_group: 'E', fifa_ranking: 10, is_debut: false },
  { name: 'Croatia',      tier: 1, flag_emoji: '🇭🇷', confederation: 'UEFA',     fifa_group: 'L', fifa_ranking: 11, is_debut: false },
  { name: 'Colombia',     tier: 1, flag_emoji: '🇨🇴', confederation: 'CONMEBOL', fifa_group: 'K', fifa_ranking: 12, is_debut: false },
  { name: 'Senegal',      tier: 1, flag_emoji: '🇸🇳', confederation: 'CAF',      fifa_group: 'I', fifa_ranking: 13, is_debut: false },
  { name: 'Mexico',       tier: 1, flag_emoji: '🇲🇽', confederation: 'CONCACAF', fifa_group: 'A', fifa_ranking: 14, is_debut: false },
  { name: 'United States',tier: 1, flag_emoji: '🇺🇸', confederation: 'CONCACAF', fifa_group: 'D', fifa_ranking: 15, is_debut: false },
  { name: 'Uruguay',      tier: 1, flag_emoji: '🇺🇾', confederation: 'CONMEBOL', fifa_group: 'H', fifa_ranking: 16, is_debut: false },
  // TIER 2 — Contenders (FIFA #17–32)
  { name: 'Japan',        tier: 2, flag_emoji: '🇯🇵', confederation: 'AFC',      fifa_group: 'F', fifa_ranking: 17, is_debut: false },
  { name: 'Switzerland',  tier: 2, flag_emoji: '🇨🇭', confederation: 'UEFA',     fifa_group: 'B', fifa_ranking: 18, is_debut: false },
  { name: 'Iran',         tier: 2, flag_emoji: '🇮🇷', confederation: 'AFC',      fifa_group: 'G', fifa_ranking: 19, is_debut: false },
  { name: 'Austria',      tier: 2, flag_emoji: '🇦🇹', confederation: 'UEFA',     fifa_group: 'J', fifa_ranking: 20, is_debut: false },
  { name: 'Ecuador',      tier: 2, flag_emoji: '🇪🇨', confederation: 'CONMEBOL', fifa_group: 'E', fifa_ranking: 21, is_debut: false },
  { name: 'South Korea',  tier: 2, flag_emoji: '🇰🇷', confederation: 'AFC',      fifa_group: 'A', fifa_ranking: 22, is_debut: false },
  { name: 'Australia',    tier: 2, flag_emoji: '🇦🇺', confederation: 'AFC',      fifa_group: 'D', fifa_ranking: 23, is_debut: false },
  { name: 'Egypt',        tier: 2, flag_emoji: '🇪🇬', confederation: 'CAF',      fifa_group: 'G', fifa_ranking: 24, is_debut: false },
  { name: 'Canada',       tier: 2, flag_emoji: '🇨🇦', confederation: 'CONCACAF', fifa_group: 'B', fifa_ranking: 25, is_debut: false },
  { name: 'Ivory Coast',  tier: 2, flag_emoji: '🇨🇮', confederation: 'CAF',      fifa_group: 'E', fifa_ranking: 26, is_debut: false },
  { name: 'Qatar',        tier: 2, flag_emoji: '🇶🇦', confederation: 'AFC',      fifa_group: 'B', fifa_ranking: 27, is_debut: false },
  { name: 'Algeria',      tier: 2, flag_emoji: '🇩🇿', confederation: 'CAF',      fifa_group: 'J', fifa_ranking: 28, is_debut: false },
  { name: 'Sweden',       tier: 2, flag_emoji: '🇸🇪', confederation: 'UEFA',     fifa_group: 'F', fifa_ranking: 29, is_debut: false },
  { name: 'Tunisia',      tier: 2, flag_emoji: '🇹🇳', confederation: 'CAF',      fifa_group: 'F', fifa_ranking: 30, is_debut: false },
  { name: 'Czechia',      tier: 2, flag_emoji: '🇨🇿', confederation: 'UEFA',     fifa_group: 'A', fifa_ranking: 31, is_debut: false },
  { name: 'Turkey',       tier: 2, flag_emoji: '🇹🇷', confederation: 'UEFA',     fifa_group: 'D', fifa_ranking: 32, is_debut: false },
  // TIER 3 — Dark Horses (FIFA #33–48)
  { name: 'Norway',                 tier: 3, flag_emoji: '🇳🇴', confederation: 'UEFA',     fifa_group: 'I', fifa_ranking: 33,  is_debut: false },
  { name: 'Scotland',               tier: 3, flag_emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', confederation: 'UEFA',     fifa_group: 'C', fifa_ranking: 34,  is_debut: false },
  { name: 'DR Congo',               tier: 3, flag_emoji: '🇨🇩', confederation: 'CAF',      fifa_group: 'K', fifa_ranking: 35,  is_debut: false },
  { name: 'Bosnia & Herzegovina',   tier: 3, flag_emoji: '🇧🇦', confederation: 'UEFA',     fifa_group: 'B', fifa_ranking: 36,  is_debut: false },
  { name: 'Panama',                 tier: 3, flag_emoji: '🇵🇦', confederation: 'CONCACAF', fifa_group: 'L', fifa_ranking: 48,  is_debut: false },
  { name: 'Saudi Arabia',           tier: 3, flag_emoji: '🇸🇦', confederation: 'AFC',      fifa_group: 'H', fifa_ranking: 50,  is_debut: false },
  { name: 'South Africa',           tier: 3, flag_emoji: '🇿🇦', confederation: 'CAF',      fifa_group: 'A', fifa_ranking: 55,  is_debut: false },
  { name: 'Iraq',                   tier: 3, flag_emoji: '🇮🇶', confederation: 'AFC',      fifa_group: 'I', fifa_ranking: 60,  is_debut: false },
  { name: 'Uzbekistan',             tier: 3, flag_emoji: '🇺🇿', confederation: 'AFC',      fifa_group: 'K', fifa_ranking: 65,  is_debut: true  },
  { name: 'Paraguay',               tier: 3, flag_emoji: '🇵🇾', confederation: 'CONMEBOL', fifa_group: 'D', fifa_ranking: 70,  is_debut: false },
  { name: 'Ghana',                  tier: 3, flag_emoji: '🇬🇭', confederation: 'CAF',      fifa_group: 'L', fifa_ranking: 75,  is_debut: false },
  { name: 'Jordan',                 tier: 3, flag_emoji: '🇯🇴', confederation: 'AFC',      fifa_group: 'J', fifa_ranking: 80,  is_debut: true  },
  { name: 'Cape Verde',             tier: 3, flag_emoji: '🇨🇻', confederation: 'CAF',      fifa_group: 'H', fifa_ranking: 85,  is_debut: true  },
  { name: 'Curacao',                tier: 3, flag_emoji: '🇨🇼', confederation: 'CONCACAF', fifa_group: 'E', fifa_ranking: 90,  is_debut: true  },
  { name: 'Haiti',                  tier: 3, flag_emoji: '🇭🇹', confederation: 'CONCACAF', fifa_group: 'C', fifa_ranking: 95,  is_debut: false },
  { name: 'New Zealand',            tier: 3, flag_emoji: '🇳🇿', confederation: 'OFC',      fifa_group: 'G', fifa_ranking: 100, is_debut: false },
];
